global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: node-exporter
    static_configs:
      - targets: [172.18.0.1:9100]
    relabel_configs:
      - target_label: instance
        replacement: mother

  - job_name: node-exporter-nostromo
    static_configs:
      - targets: [10.0.0.250:9100]
    relabel_configs:
      - target_label: instance
        replacement: nostromo

  - job_name: sync-webhook
    static_configs:
      - targets: [sync-webhook:5000]
    metrics_path: /metrics
    relabel_configs:
      - target_label: instance
        replacement: mother

  - job_name: unifi-exporter
    static_configs:
      - targets: [unifi-exporter:9110]

  - job_name: docker-stats-exporter
    static_configs:
      - targets: [docker-stats-exporter:9330]
    relabel_configs:
      - target_label: instance
        replacement: mother
