#!/bin/bash
# Snapshot host state that lives OUTSIDE /opt/mother into a directory that IS
# backed up, so a Mother rebuild doesn't depend on anything that was never captured.
#
# WHY: Backrest's plan backs up /opt/mother only. On 2026-09-01 that was found to
# leave out precisely the things needed to rebuild the host:
#   * the crontab (VPN monitor, container watchdog, daily reports, this script)
#   * /etc/fstab — every NFS/CIFS mount definition for both Synologys and Unraid
#   * ~/.ssh private keys — SSH to the download Synology, Unraid and Nostromo
#   * /etc/samba/credentials_unraid — the Unraid CIFS credentials
#   * /etc/systemd/system/mother-sync.service and the .mount units
# Without these a restore gives you the application back but not a working host.
#
# Output goes to /opt/mother/data/host-state/, which is inside the backup plan's
# path and is NOT in its exclude list.
#
# NOTE: this captures PRIVATE SSH KEYS. That is deliberate — they are required for
# disaster recovery and the restic repository is encrypted. The directory is 0700
# and every file 0600. .env (which already holds every API key) is in the same
# backup, so this does not widen the blast radius.
#
# Cron: 50 3 * * *  — ten minutes before the 04:00 Backrest run.
set -uo pipefail

DEST=/opt/mother/data/host-state
mkdir -p "$DEST"
chmod 700 "$DEST"

{
  echo "# Captured $(date -Is) on $(hostname)"
  echo "# Regenerated by scripts/snapshot_host_state.sh — do not edit by hand."
} > "$DEST/README.txt"

crontab -l                      > "$DEST/crontab.alig.txt"       2>/dev/null
cp -f /etc/fstab                  "$DEST/fstab"                  2>/dev/null
# /etc/samba/credentials_unraid is 0600 root:root, so this script (running as
# alig) cannot read it. Record the gap explicitly rather than silently omitting
# it — a restore needs to know to recreate it. Contents are just the Unraid SMB
# username/password, which Ali has.
if cp -f /etc/samba/credentials_unraid "$DEST/credentials_unraid" 2>/dev/null; then
  :
else
  echo "NOT CAPTURED: /etc/samba/credentials_unraid (root-only, 0600 root:root)." \
       "Recreate it on restore — it holds the Unraid SMB username/password and is" \
       "referenced by the //192.168.1.10/Media line in fstab." \
       > "$DEST/MISSING-credentials_unraid.txt"
fi
cp -f /home/alig/.ssh/config      "$DEST/ssh_config"             2>/dev/null

mkdir -p "$DEST/ssh"
cp -f /home/alig/.ssh/*key /home/alig/.ssh/*key.pub \
      /home/alig/.ssh/authorized_keys "$DEST/ssh/" 2>/dev/null

mkdir -p "$DEST/systemd"
cp -f /etc/systemd/system/mother*.service \
      /etc/systemd/system/*.mount "$DEST/systemd/" 2>/dev/null

# Useful for rebuilding, cheap to capture.
docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.Status}}' > "$DEST/containers.txt" 2>/dev/null
ip -br addr                                                 > "$DEST/ip_addr.txt"    2>/dev/null
mount | grep -E 'nfs|cifs'                                  > "$DEST/mounts.txt"     2>/dev/null
dpkg -l 2>/dev/null | awk '/^ii/{print $2"\t"$3}'           > "$DEST/packages.txt"

chmod -R go-rwx "$DEST"
find "$DEST" -type f -exec chmod 600 {} +
find "$DEST" -type d -exec chmod 700 {} +

echo "host state captured -> $DEST ($(find "$DEST" -type f | wc -l) files)"
